### ISSUE TITLE
Fix inconsistent loading in dictionary creator

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#12]
## Expected behavior
The `dictionary_creator` loads a consistent progress (i.e., it continues with the same data that has been saved).

## Actual behavior
The `dictionary_creator` loads incomplete progress (e.g., `word_graph`).

## Tasks
- [x] Implement `self.progress_log = []` that stores all completed steps.
- [x] Assert consistent loading
- [x] Add a test for inconsistent loading
- [x] Check that test coverage is >= 98%
- [x] Look at `todo`s in comments
- [ ] Review all changes and merge
