### ISSUE TITLE
Try out AWESoME/eflomal word aligner

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#14]
![image](https://user-images.githubusercontent.com/12159412/216100745-2717430e-cb6a-4f32-b325-64c637ddac5f.png)
![image](https://user-images.githubusercontent.com/12159412/216100882-1a5554df-43a0-43f6-a558-bacb99752f63.png)

## Goal
As a software developer, I want to try out replacing fast_align with the AWESoME word aligner to see if this improves the dictionary creator's F1 score.
Motivation: improve alignment -> reduce FPs -> increase DC's precision

## Tasks
- [x] Install awesome align
- [x] Adapt `dictionary_creator` to use eflomal instead of fast_align
- [x] Evaluate DC for eng-fra, eng-tpi without fine-tuning
- [x] Evaluate DC for eng-meu without fine-tuning
- [ ] Fine-tune DC for eng-tpi on with [NVIDIA/CUDA GPU](https://www.geeksforgeeks.org/how-to-set-up-and-run-cuda-operations-in-pytorch/) or cluster (takes ~70h on notebook CPU)
  - [ ] https://gitlab.hpi.de/aiis/knowledge-base/-/blob/main/usage.md
- [ ] Fine-tune DC for eng-meu
- [ ] Evaluate DC for eng-fra, eng-tpi, eng-meu with fine-tuning
- [ ] (Create follow-Up issue: Try out Wada/SimAlign/eflomal)
- [ ] Try out Eflomal word aligner

## F1* / MRR
| Language pair | fast_align (baseline) | mBERT | fine-tuned by [AWESoME](https://github.com/neulab/awesome-align) | Eflomal |
| :--- | :--- | :--- | :--- | :--- |
| eng-eng |0.25, **0.40**|0.26, 0.38|**0.27**, 0.38| 0.23, 0.39 |
| eng-fra |0.24, 0.37|**0.27**, 0.38|**0.27**, 0.36|0.26, **0.41** |
| eng-tpi|n/a, 0.28|n/a, 0.19|n/a, 0.20|n/a, **0.31**|
| eng-meu|n/a, **0.23**|n/a, 0.11|n/a, 0.11|n/a, 0.21|
