### ISSUE TITLE
Acquire parallel data from Bloom Library

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#15]
![image](https://user-images.githubusercontent.com/12159412/216012550-6eb175be-c396-48be-988f-1968f6c41ed4.png)
(https://huggingface.co/datasets/sil-ai/bloom-lm/viewer/tpi/train)

## Goal
As a developer, I want to use books from the bloom library as supplementary training data to improve the word alignment's quality. This would successively increase the dictionary creator's precision.
Motivation: (More data beats more clever algorithms.) more parallel data -> improve alignment -> less FPs -> higher DC precision

## Example
`The Story of Jonah`
eng: `In those days there was a very large town where many people lived. The town's name was Nineveh.`
tpi: `Long dispela taim i gat wanpela bikpela taun i gat planti manmeri. Nem bilong dispela taun em Nineveh.`

## Tasks
- [x] search for parallel texts on https://bloomlibrary.org/
  - 10,000+ books
  - 500+ languages
- [x] check https://huggingface.co/datasets/sil-ai/bloom-lm
- [x] check https://bloomlibrary.org/language:tpi
- [x] check https://bloomlibrary.org/page/create/linux
- [ ] ~~align these texts~~
  - [x] ask Joshua if there already exists an alignment
- [ ] use https://huggingface.co/datasets/sil-ai/bloom-captioning
