### ISSUE TITLE
Include semantic domains in graph

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#18]
![image](https://user-images.githubusercontent.com/12159412/217014038-1cc14cdb-71e2-4835-8dd9-be8428282307.png)

## Goal
There are ~8000 more nodes in the graph: Each is a semantic domain (question), with links to each of its words in different languages. Creating dictionaries means finding these links.
Motivation: build GNN -> increase DC precision and recall > 0.30

## Tasks
- [x] Move the whole graph structure to NetworkX.
- [x] Add semantic domain questions.
- [ ] Add semantic domains.
- [ ] (Without GNN: For each target word, add the semantic domains of all its translation candidates and select the most likely ones.)
- [ ] Compare both approaches.

## Notes
- give up 1:1 idea
- idea shift: map a group of words in one lang to a group of words in another language?
- For example, we could recognize `eng:polluted` by adding the two connections to `4.9.5.6`.

**Comment by janetzki** [comment]
Did not lead to useful predictions.
