### ISSUE TITLE
Use word embeddings for English and LRL

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#28]
## Goal
We compute word embeddings for English words, fra/tpi/meu words, and semantic domains (by averaging the English words) to link the fra/tpi/meu words to the semantic domains.
(This issue is not part of the proposal. --> optional)
Motivation: less FP, less FN --> more precision and recall --> F1 > 0.30

## Tasks
- [x] clarify the goal
- [ ] Does the aligner (e.g., a fine-tuned AWESoME model) already use word embeddings?
- [ ] clarify how this is different from node embeddings if words are nodes
- [ ] look at [Neural Cross-Lingual NER with Minimal Resources](https://github.com/thespectrewithin/cross-lingual_NER)
  - [ ] try out MUSE
- [ ] get word embeddings for English words (e.g., word2vec/Glove)
- [ ] compute word embeddings for semantic domains
- [ ] compute word embeddings for fra/LRL words
- [ ] link fra/tpi/meu words to semantic domains
- [ ] evaluate created dictionaries

**Comment by janetzki** [comment]
Closed because completion on time is not realistic.
