### ISSUE TITLE
Build simple model for Semantic Domain Identification

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#29]
## Goal
We want to build a simple model for SDI that serves as a baseline.
Motivation: SDI with F1 > 0.30 for 1 tpi/meu

## Tasks
- [ ] Acquire mappings from verses to semantic domains #1 
- [x] look up each word in a dictionary (see proposal: A.3.2.1 Dictionary Lookup)
- [x] Add a test for semantic domain identifier
- [x] Check that test coverage is >= 98%
- [x] Look at `todo`s in comments
