### ISSUE TITLE
Build language information graph

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#31]
## Goal
We want to use a tree-structured graph that contains languages and their linguistic and geographic relations. We hypothesize that this improves the performance of the GNN-based edge prediction model for dictionary creation.

## Tasks
- [ ] see A.1.4 in proposal
- [ ] acquire and parse language information in Ethnologue
- [ ] acquire and parse language information in WALS

**Comment by janetzki** [comment]
Closed because completion on time is not realistic.
