### ISSUE TITLE
Get Tok Pisin and Suau/Duai dictionaries

### ISSUE THREAD

**Issue by janetzki** [janetzki/dictionary_creator#8]
## Goal
We have one dictionary for Tok Pisin (tpi) and Suau/Duai (swp) that I can use to evaluate the dictionary creator on these two LRLs (and not only on HRL/MRL).

## Tasks
- [x] check which data we already have
- [x] create a parsable list of translations between Tok Pisin and English
- [x] create a parsable list of translations between Suau/Duai and English
- [ ] (if needed, parse PDFs with `tabula-py` lib)
  - [ ] (categorize rows according to language)
- [ ] (if needed, read https://bytescout.com/articles/how-to-extract-pdf-with-multiple-columns-to-text-using-pdf-multitool)
- [ ] optional: send parsable dictionaries back to creators

## Notes
- Why did we choose Tok Pisin and Duai?
  - a) We have aligned bibles in these languages.
  - b) SIL has [language projects](https://public.languagedepot.org/projects) (and experts) for these languages.
- Suau ~ Duai
